<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ApplicationIcon>Assets\Ameko.ico</ApplicationIcon>
    <NoWarn>AVLN3001</NoWarn>
    <LangVersion>14</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.AvaloniaEdit" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" />
    <PackageReference Include="Avalonia.Controls.DataGrid" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.HtmlRenderer" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Avalonia.Themes.Simple" />
    <PackageReference Include="AvaloniaEdit.TextMate" />
    <PackageReference Include="Ben.Demystifier" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="CS-Script" />
    <PackageReference Include="CSharpier.MsBuild">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="DiscordRichPresence" />
    <PackageReference Include="FuzzySharp" />
    <PackageReference Include="GitInfo">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Jint" />
    <PackageReference Include="Markdig" />
    <PackageReference Include="Markdown.Avalonia.Tight" />
    <PackageReference Include="Markdown.ColorCode" />
    <PackageReference Include="Material.Icons.Avalonia" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="NLog" />
    <PackageReference Include="NLog.Extensions.Logging" />
    <PackageReference Include="ReactiveUI.Avalonia" />
    <PackageReference Include="Semi.Avalonia" />
    <PackageReference Include="Semi.Avalonia.AvaloniaEdit" />
    <PackageReference Include="Semi.Avalonia.ColorPicker" />
    <PackageReference Include="Semi.Avalonia.DataGrid" />
    <PackageReference Include="Semi.Avalonia.Tabalonia" />
    <PackageReference Include="Semver" />
    <PackageReference Include="Silk.NET.OpenAL" />
    <PackageReference Include="Silk.NET.OpenAL.Extensions.EXT" />
    <PackageReference Include="Silk.NET.OpenAL.Extensions.Soft" />
    <PackageReference Include="Silk.NET.OpenAL.Soft.Native" />
    <PackageReference Include="Silk.NET.OpenGLES" />
    <PackageReference Include="Tabalonia" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AssCS\AssCS.csproj" />
    <ProjectReference Include="..\Holo\Holo.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Views\Windows\MainWindow.axaml.cs">
      <DependentUpon>MainWindow.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="ViewModels\Windows\MainWindowViewModel.Commands.cs">
      <DependentUpon>MainWindowViewModel.cs</DependentUpon>
    </Compile>
    <Compile Update="ViewModels\Controls\TabItemViewModel.Commands.cs">
      <DependentUpon>TabItemViewModel.cs</DependentUpon>
    </Compile>
    <Compile Update="ViewModels\Windows\StylesManagerWindowViewModel.Commands.cs">
      <DependentUpon>StylesManagerWindowViewModel.cs</DependentUpon>
    </Compile>
    <Compile Update="ViewModels\Windows\PkgManWindowViewModel.commands.cs">
      <DependentUpon>PkgManWindowViewModel.cs</DependentUpon>
    </Compile>
    <Compile Update="Views\Controls\RepositoryInformation.axaml.cs">
      <DependentUpon>RepositoryInformation.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\StyleEditor.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\About.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>About.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\PkgMan.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PkgMan.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\StylesManager.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>StylesManager.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\Other.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Other.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\ShiftTimes.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\PasteOver.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>PasteOver.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\Git.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Git.resx</DependentUpon>
    </Compile>
    <Compile Update="ViewModels\Controls\GitToolboxViewModel.Commands.cs">
      <DependentUpon>GitToolboxViewModel.cs</DependentUpon>
    </Compile>
    <Compile Update="I18N\Jump.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Jump.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\Keybinds.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Keybinds.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\FileModified.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>FileModified.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\SearchDialog.axaml.cs">
      <DependentUpon>SearchDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\Search.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Search.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\InstallDictionaryDialog.axaml.cs">
      <DependentUpon>InstallDictionaryDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\Spellcheck.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\SpellcheckDialog.axaml.cs">
      <DependentUpon>SpellcheckDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\Playground.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Playground.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\StyleEditorDialog.axaml.cs">
      <DependentUpon>StyleEditorDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\KeybindsDialog.axaml.cs">
      <DependentUpon>KeybindsDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\Config.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Config.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\ProjectConfigDialog.axaml.cs">
      <DependentUpon>ProjectConfigDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\ChangelogDialog.axaml.cs">
      <DependentUpon>ChangelogDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\SelectDialog.axaml.cs">
      <DependentUpon>SelectDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\SortDialog.axaml.cs">
      <DependentUpon>SortDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\ScriptInfoDialog.axaml.cs">
      <DependentUpon>ScriptInfoDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\ScriptInfo.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </Compile>
    <Compile Update="Views\Dialogs\SelectFolderDialog.axaml.cs">
      <DependentUpon>SelectFolderDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Dialogs\CommandPaletteDialog.axaml.cs">
      <DependentUpon>CommandPaletteDialog.axaml</DependentUpon>
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="I18N\CommandPalette.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </Compile>
    <Compile Update="I18N\Knp.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Knp.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="I18N\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>StyleEditor.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>About.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PkgMan.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>StylesManager.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Other.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ShiftTimes.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>PasteOver.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Git.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Jump.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Keybinds.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>FileModified.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Search.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Spellcheck.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Playground.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Config.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>ScriptInfo.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>CommandPalette.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.de-DE.resx">
      <DependentUpon>About.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.en-GB.resx">
      <DependentUpon>About.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.es-419.resx">
      <DependentUpon>About.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.pl-PL.resx">
      <DependentUpon>About.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.vi-VN.resx">
      <DependentUpon>About.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\About.zh-TW.resx">
      <DependentUpon>About.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.de-DE.resx">
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.en-GB.resx">
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.es-419.resx">
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.pl-PL.resx">
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.vi-VN.resx">
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\CommandPalette.zh-TW.resx">
      <DependentUpon>CommandPalette.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.de-DE.resx">
      <DependentUpon>Config.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.en-GB.resx">
      <DependentUpon>Config.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.es-419.resx">
      <DependentUpon>Config.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.pl-PL.resx">
      <DependentUpon>Config.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.vi-VN.resx">
      <DependentUpon>Config.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Config.zh-TW.resx">
      <DependentUpon>Config.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.de-DE.resx">
      <DependentUpon>FileModified.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.en-GB.resx">
      <DependentUpon>FileModified.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.es-419.resx">
      <DependentUpon>FileModified.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.pl-PL.resx">
      <DependentUpon>FileModified.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.vi-VN.resx">
      <DependentUpon>FileModified.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\FileModified.zh-TW.resx">
      <DependentUpon>FileModified.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.de-DE.resx">
      <DependentUpon>Git.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.en-GB.resx">
      <DependentUpon>Git.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.es-419.resx">
      <DependentUpon>Git.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.pl-PL.resx">
      <DependentUpon>Git.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.vi-VN.resx">
      <DependentUpon>Git.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Git.zh-TW.resx">
      <DependentUpon>Git.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.de-DE.resx">
      <DependentUpon>Help.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.en-GB.resx">
      <DependentUpon>Help.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.es-419.resx">
      <DependentUpon>Help.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.pl-PL.resx">
      <DependentUpon>Help.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.vi-VN.resx">
      <DependentUpon>Help.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Help.zh-TW.resx">
      <DependentUpon>Help.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.de-DE.resx">
      <DependentUpon>Jump.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.en-GB.resx">
      <DependentUpon>Jump.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.es-419.resx">
      <DependentUpon>Jump.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.pl-PL.resx">
      <DependentUpon>Jump.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.vi-VN.resx">
      <DependentUpon>Jump.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Jump.zh-TW.resx">
      <DependentUpon>Jump.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.de-DE.resx">
      <DependentUpon>Keybinds.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.en-GB.resx">
      <DependentUpon>Keybinds.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.es-419.resx">
      <DependentUpon>Keybinds.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.pl-PL.resx">
      <DependentUpon>Keybinds.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.vi-VN.resx">
      <DependentUpon>Keybinds.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Keybinds.zh-TW.resx">
      <DependentUpon>Keybinds.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.de-DE.resx">
      <DependentUpon>Other.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.en-GB.resx">
      <DependentUpon>Other.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.es-419.resx">
      <DependentUpon>Other.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.pl-PL.resx">
      <DependentUpon>Other.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.vi-VN.resx">
      <DependentUpon>Other.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Other.zh-TW.resx">
      <DependentUpon>Other.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.de-DE.resx">
      <DependentUpon>PasteOver.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.en-GB.resx">
      <DependentUpon>PasteOver.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.es-419.resx">
      <DependentUpon>PasteOver.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.pl-PL.resx">
      <DependentUpon>PasteOver.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.vi-VN.resx">
      <DependentUpon>PasteOver.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PasteOver.zh-TW.resx">
      <DependentUpon>PasteOver.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.de-DE.resx">
      <DependentUpon>PkgMan.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.en-GB.resx">
      <DependentUpon>PkgMan.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.es-419.resx">
      <DependentUpon>PkgMan.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.pl-PL.resx">
      <DependentUpon>PkgMan.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.vi-VN.resx">
      <DependentUpon>PkgMan.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\PkgMan.zh-TW.resx">
      <DependentUpon>PkgMan.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.de-DE.resx">
      <DependentUpon>Playground.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.en-GB.resx">
      <DependentUpon>Playground.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.es-419.resx">
      <DependentUpon>Playground.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.pl-PL.resx">
      <DependentUpon>Playground.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.vi-VN.resx">
      <DependentUpon>Playground.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Playground.zh-TW.resx">
      <DependentUpon>Playground.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Resources.de-DE.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Resources.en-GB.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Resources.es-419.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Resources.pl-PL.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Resources.vi-VN.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Resources.zh-TW.resx">
      <DependentUpon>Resources.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.de-DE.resx">
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.en-GB.resx">
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.es-419.resx">
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.pl-PL.resx">
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.vi-VN.resx">
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ScriptInfo.zh-TW.resx">
      <DependentUpon>ScriptInfo.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.de-DE.resx">
      <DependentUpon>Search.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.en-GB.resx">
      <DependentUpon>Search.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.es-419.resx">
      <DependentUpon>Search.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.pl-PL.resx">
      <DependentUpon>Search.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.vi-VN.resx">
      <DependentUpon>Search.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Search.zh-TW.resx">
      <DependentUpon>Search.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.de-DE.resx">
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.en-GB.resx">
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.es-419.resx">
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.pl-PL.resx">
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.vi-VN.resx">
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\ShiftTimes.zh-TW.resx">
      <DependentUpon>ShiftTimes.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.de-DE.resx">
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.en-GB.resx">
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.es-419.resx">
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.pl-PL.resx">
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.vi-VN.resx">
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Spellcheck.zh-TW.resx">
      <DependentUpon>Spellcheck.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.de-DE.resx">
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.en-GB.resx">
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.es-419.resx">
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.pl-PL.resx">
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.vi-VN.resx">
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StyleEditor.zh-TW.resx">
      <DependentUpon>StyleEditor.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.de-DE.resx">
      <DependentUpon>StylesManager.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.en-GB.resx">
      <DependentUpon>StylesManager.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.es-419.resx">
      <DependentUpon>StylesManager.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.pl-PL.resx">
      <DependentUpon>StylesManager.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.vi-VN.resx">
      <DependentUpon>StylesManager.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\StylesManager.zh-TW.resx">
      <DependentUpon>StylesManager.resx</DependentUpon>
    </EmbeddedResource>
    <EmbeddedResource Update="I18N\Knp.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Knp.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <ItemGroup>
      <MIZUKI
        Condition="$([MSBuild]::IsOSPlatform('Windows'))"
        Include="$(SolutionDir)Mizuki\zig-out\bin\*.*"
      />
      <MIZUKI
        Condition="$([MSBuild]::IsOSPlatform('OSX')) or $([MSBuild]::IsOSPlatform('Linux'))"
        Include="$(SolutionDir)Mizuki\zig-out\lib\*.*"
      />
    </ItemGroup>
    <Copy SourceFiles="@(MIZUKI)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>
  <Target Name="PostPublish" AfterTargets="Publish">
    <ItemGroup>
      <MIZUKI
        Condition="$([MSBuild]::IsOSPlatform('Windows'))"
        Include="$(SolutionDir)Mizuki\zig-out\bin\*.*"
      />
      <MIZUKI
        Condition="$([MSBuild]::IsOSPlatform('OSX')) or $([MSBuild]::IsOSPlatform('Linux'))"
        Include="$(SolutionDir)Mizuki\zig-out\lib\*.*"
      />
    </ItemGroup>
    <Copy SourceFiles="@(MIZUKI)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
