//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Knp {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Knp() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Knp", typeof(Knp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string KnpWindow_Title {
            get {
                return ResourceManager.GetString("KnpWindow_Title", resourceCulture);
            }
        }
        
        public static string Knp_ContextMenu_Delete {
            get {
                return ResourceManager.GetString("Knp_ContextMenu_Delete", resourceCulture);
            }
        }
        
        public static string Knp_Button_AddTerm {
            get {
                return ResourceManager.GetString("Knp_Button_AddTerm", resourceCulture);
            }
        }
        
        public static string Knp_Header_Category {
            get {
                return ResourceManager.GetString("Knp_Header_Category", resourceCulture);
            }
        }
        
        public static string Knp_Header_Context {
            get {
                return ResourceManager.GetString("Knp_Header_Context", resourceCulture);
            }
        }
        
        public static string Knp_Header_Original {
            get {
                return ResourceManager.GetString("Knp_Header_Original", resourceCulture);
            }
        }
        
        public static string Knp_Header_Alternate {
            get {
                return ResourceManager.GetString("Knp_Header_Alternate", resourceCulture);
            }
        }
        
        public static string Knp_Header_Translation {
            get {
                return ResourceManager.GetString("Knp_Header_Translation", resourceCulture);
            }
        }
        
        public static string Knp_Header_Notes {
            get {
                return ResourceManager.GetString("Knp_Header_Notes", resourceCulture);
            }
        }
        
        public static string Knp_Header_CaseSensitive {
            get {
                return ResourceManager.GetString("Knp_Header_CaseSensitive", resourceCulture);
            }
        }
    }
}
