//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ameko.I18N {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Profiler {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Profiler() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ameko.I18N.Profiler", typeof(Profiler).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Profiler_Title {
            get {
                return ResourceManager.GetString("Profiler_Title", resourceCulture);
            }
        }
        
        public static string Profiler_Button_Export {
            get {
                return ResourceManager.GetString("Profiler_Button_Export", resourceCulture);
            }
        }
        
        public static string Profiler_Button_Start {
            get {
                return ResourceManager.GetString("Profiler_Button_Start", resourceCulture);
            }
        }
        
        public static string Profiler_RB_All {
            get {
                return ResourceManager.GetString("Profiler_RB_All", resourceCulture);
            }
        }
        
        public static string Profiler_RB_SelectedTimeRange {
            get {
                return ResourceManager.GetString("Profiler_RB_SelectedTimeRange", resourceCulture);
            }
        }
        
        public static string Profiler_RB_SelectedEvents {
            get {
                return ResourceManager.GetString("Profiler_RB_SelectedEvents", resourceCulture);
            }
        }
        
        public static string Profiler_CheckBox_UseVideoRes {
            get {
                return ResourceManager.GetString("Profiler_CheckBox_UseVideoRes", resourceCulture);
            }
        }
        
        public static string Profiler_Axis_RenderTime {
            get {
                return ResourceManager.GetString("Profiler_Axis_RenderTime", resourceCulture);
            }
        }
        
        public static string Profiler_Axis_ImageSize {
            get {
                return ResourceManager.GetString("Profiler_Axis_ImageSize", resourceCulture);
            }
        }
        
        public static string Profiler_Axis_ImageCount {
            get {
                return ResourceManager.GetString("Profiler_Axis_ImageCount", resourceCulture);
            }
        }
        
        public static string Profiler_Axis_Frame {
            get {
                return ResourceManager.GetString("Profiler_Axis_Frame", resourceCulture);
            }
        }
        
        public static string Profiler_Description {
            get {
                return ResourceManager.GetString("Profiler_Description", resourceCulture);
            }
        }
        
        public static string Profiler_Label_FontDirectories {
            get {
                return ResourceManager.GetString("Profiler_Label_FontDirectories", resourceCulture);
            }
        }
        
        public static string Profiler_Label_Settings {
            get {
                return ResourceManager.GetString("Profiler_Label_Settings", resourceCulture);
            }
        }
    }
}
